#!/bin/bash
source "/data/SetupHelper/CommonResources"
if [ $scriptAction == 'NONE' ] ; then
	echo 'Integrates GS into Victron'
	standardActionPrompt
fi
if [ $scriptAction == 'INSTALL' ] ; then
	mkdir /opt/gs
	cp *.py /opt/gs/

	rsync -a /opt/victronenergy/service-templates/openssh /service/venus-gs
	cp service.run /service/venus-gs/run

	installService $packageName
fi
if [ $scriptAction == 'UNINSTALL' ] ; then
	echo rm -rf /opt/gs
	rm -rf /service/venus-gs

	removeService $packageName
fi

endScript
